FROM lcr.loongnix.cn/library/debian:sid

# install essential tools
RUN apt update && apt install -y wget git make libvirt-dev

ADD lib lib

# Install dependencies with lib

# Install golang
RUN apt install -y curl && cd lib && ./install-golang.sh 22

