FROM cr.loongnix.cn/openanolis/anolisos:8.8

# install essential tools
RUN yum update -y && \
  yum install git curl -y

ADD lib lib

# Install dependencies with lib
RUN ./lib/install-java.sh 8
## 
RUN ./lib/install-maven.sh 3.3.9

# Install packages
RUN yum install -y patch python2 rpm rpm-build gcc gcc-c++ platform-python-devel glibc-devel python3-devel python2-devel
RUN ln -s /usr/bin/python2 /usr/bin/python &&  alias python2='/usr/bin/python2' && alias python=python2 
