FROM cr.loongnix.cn/openanolis/anolisos:8.8

# install essential tools
RUN yum update -y && \
  yum install git curl -y

ADD deps deps

# Install dependencies with lib
RUN ./deps/install-java.sh 8
## 
RUN ./deps/install-maven.sh 3.5.4

# Install packages
RUN ./deps/install-rpm.sh

# Install protobuf 2.5.0
RUN ./deps/install-protobuf.sh

ENV JAVA_HOME /usr/local/java

ENV PATH="/usr/local/java/bin:/usr/local/maven/bin:$PATH"
