FROM lcr.loongnix.cn/openeuler/openeuler:22.03-LTS

# install essential tools
RUN yum update -y && \
  yum install git curl make tar -y

ADD lib lib

# Install dependencies with lib
## RUN ./lib/install-java.sh 8
## 
## RUN ./lib/install-maven.sh 3.6.3
##
RUN cd lib && ./install-golang.sh 20

# Install packages
## RUN yum install -y xxx

