FROM cr.loongnix.cn/loongson/loongnix-server:8.4

# install essential tools
RUN yum makecache && \
  yum install git curl -y


## 安装相关依赖
RUN yum install -y gcc gcc-c++ make cmake loongnix-release-epel git java-1.8.0-openjdk-devel flex maven asciidoc unixODBC unixODBC-devel golang-1.18 zlib-devel xz-devel snappy-devel jansson-devel pkgconfig libatomic libstdc++-static libatomic-static zlib-static wget

