FROM cr.loongnix.cn/openanolis/anolisos:8.8

# install essential tools
RUN yum update -y && \
  yum install git curl -y

ADD lib lib

# Install dependencies with lib
RUN ./lib/install-java.sh 8
## 
RUN ./lib/install-maven.sh 3.5.4

# Install packages
RUN yum install -y python2

ENV JAVA_HOME /usr/local
