FROM cr.loongnix.cn/library/golang:1.21-alpine

# install essential tools
RUN apk update && \
  apk add git curl make bash


# Install dependencies with lib
## RUN ./lib/install-java.sh 8
## 
## RUN ./lib/install-maven.sh 3.6.3

# Install packages
## RUN yum install -y xxx
