FROM lcr.loongnix.cn/library/golang:1.21-buster

# install essential tools
RUN apt update -y && \
  apt install git curl wget -y

ADD lib lib

# Install dependencies with lib
## RUN ./lib/install-java.sh 8
## 
## RUN ./lib/install-maven.sh 3.6.3

# Install packages
## RUN yum install -y xxx
