FROM lcr.loongnix.cn/library/alpine:3.19

# install essential tools
RUN apk update && apk add curl bash

ADD lib lib

# Install dependencies with lib

# Install golang
RUN cd lib && ./install-golang.sh 22
