FROM cr.loongnix.cn/openanolis/anolisos:8.8

# install essential tools
RUN yum update -y && \
  yum install git curl -y

ADD lib lib
ADD deps deps

# Install dependencies with lib
RUN ./deps/install-java.sh 8
#RUN ./lib/install-java.sh 8
## 
RUN ./lib/install-maven.sh 3.6.3

# Install packages
RUN yum install -y patch gcc gcc-c++ glibc-devel
ENV PATH=/usr/local/java/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
