FROM lcr.loongnix.cn/library/debian:sid

# install essential tools
RUN apt update && apt install -y wget git make

ADD lib lib

# Install dependencies with lib

# Install golang
RUN apt install -y curl docker-cli && cd lib && ./install-golang.sh 20

