FROM cr.loongnix.cn/openanolis/anolisos:8.8

# install essential tools
RUN yum update -y && \
  yum install git curl -y

ADD lib lib

# Install dependencies with lib
RUN ./lib/install-java.sh 8

RUN ./lib/install-maven.sh 3.6.3

# Install packages
RUN yum install -y python3 libatomic gcc gcc-c++

RUN echo "registry =https://registry.loongnix.cn:4873" >> ~/.npmrc
